spring:
  datasource:
    url: jdbc:mysql://120.48.2.40:3306/kuaiwu?serverTimezone=UTC
    username: root
    password: teapot0033
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html